version: "3.4"

services:
  db-mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=tjpass
      - MYSQL_DATABASE=dockerApp
      - MYSQL_USER=tj
      - MYSQL_PASSWORD=tjpass
    volumes:
      - db-data:/var/lib/mysql

  springbootdocker:
    build: .
    image: springbootapp
    environment:
      - DATABASE_HOST=db-mysql
      - DATABASE_USER=tj
      - DATABASE_PASSWORD=tjpass
      - DATABASE_NAME=dockerApp
      - DATABASE_PORT=3306
    depends_on:
      - db-mysql
    ports:
      - 8088:8088
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/bm/actuator/health"]
      interval: 60s
      timeout: 10s
      retries: 3
  adminer:
    image: adminer:4.7
    depends_on:
      - db-mysql
    restart: always
    ports:
      - 8080:8080
volumes:
  db-data:
